---

- name: Copy package to server
  copy:
     src: "{{ cntlm_package_file }}"
     dest: "/tmp/{{ cntlm_package_file | basename }}"
  when: cntlm_package_file is defined

- include: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include: install-debian.yml
  when: ansible_os_family == 'Debian'  

- name: Setting up CNTLM configuration
  template: >
    src={{ cntlm_config_template }}
    dest={{ cntlm_config_file }}
    owner=0
    group=0
    mode=0600
  notify: Restart CNTLM service

- name: Ensure CNTLM service is running
  service: >
    name={{ cntlm_service_name }} 
    state=started 
    enabled=yes
